bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
  install_script: bundle update

remark_task:
  container:
    image: node
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_OS
      - node -v
      - cat package.json
  install_script: npm install
  lint_script: npm run remark
  only_if: ($CIRRUS_BRANCH == 'master') ||
    changesInclude(
      '.cirrus.yml', 'package.json', '.remarkrc.yaml', '**/*.md'
    )

rubocop_task:
  container:
    image: ruby:latest
  <<: *bundle_cache
  rubocop_script: bundle exec rubocop

test_task:
  depends_on:
    - remark
    - rubocop
  container:
    matrix:
      image: ruby:2.5
      image: ruby:2.6
      image: ruby:2.7
  <<: *bundle_cache
  # environment:
  #   CODECOV_TOKEN: ENCRYPTED[...]
  test_script: bundle exec rake
