# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development do
	gem 'pry-byebug', '~> 3.9'
end

group :development, :test do
	gem 'rspec', '~> 3.9'
	gem 'simplecov', '~> 0.22.0'
	gem 'simplecov-cobertura', '~> 2.1'
end

group :development, :lint do
	gem 'rubocop', '~> 1.80.0'
	gem 'rubocop-performance', '~> 1.25.0'
	gem 'rubocop-rspec', '~> 3.6.0'
end
